print("Aca se va hacer el ejercicio 1")
print("Aca se va hacer el ejercicio 1")
print("Aca se va hacer el ejercicio 1")
print("Aca se va hacer el ejercicio 1")
print("Aca se va hacer el ejercicio 1")
print("Aca se va hacer el ejercicio 1")